apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: full-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:5000/frontend:latest
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://backend-nginx:8080  # nginx внутри кластера
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASS
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_FROM
            - name: TO_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TO_EMAIL
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: full-proj
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort   # чтобы можно было открыть через minikube
